version: '3'

services:
  app:
    build: .
    ports:
      - "4500:4500"
    volumes:
      - .:/app # This line mounts your local directory to the container
    environment:
      - NODE_ENV=development
